### ISSUE TITLE
HA not responsive when heatpump is offline

### ISSUE THREAD

**Issue by 928driver** [goev/AlsavoProHomeAssistantIntegration#2]
My HA froze when the heatpump was offline. After I powered up the heatpump, HA started working again.

**Comment by goev** [comment]
I've tried to make the code more asynchronous now. It seems much more stable now, but I haven't had the opportunity to check with the heatpump offline, but I belive it should work now.

**Comment by goev** [comment]
I've been running the newest version for almost a month now. No instability so I'll close this.
